name: Update PM2 Status from Remote Server

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Fetch pm2_status.json from remote server
      run: scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@ec2-13-36-210-197.eu-west-3.compute.amazonaws.com:/home/ec2-user/pm2_status.json pm2_status.json

    - name: Checkout GitHub Pages repository
      uses: actions/checkout@v2
      with:
        repository: tachsin/tachsin.github.io
        ref: main

    - name: Copy pm2_status.json to gh-pages
      run: |
        cp pm2_status.json tachsin.github.io/pm2_status.json
        cd tachsin.github.io
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add pm2_status.json
        git commit -m "Update PM2 status"
        git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/tachsin/tachsin.github.io.git HEAD:main
