name: Push PM2 Status

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  push_pm2_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy PM2 status file from remote machine
        run: scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@ec2-13-36-210-197.eu-west-3.compute.amazonaws.com:/home/ec2-user/pm2_status.json pm2_status.json

      - name: Commit and push PM2 status file
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pm2_status.json
          git commit -m "Update PM2 status"
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/tachsin/tachsin.github.io.git HEAD:main
